### PR TITLE
Update pytest-xdist to 1.15.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hey @jakirkham,

The CircleCI build is failing with this error:

```
===== pytest-xdist-1.15.0-py27_0 OK =====
TEST END: pytest-xdist-1.15.0-py27_0
INFO:/opt/conda/lib/python3.5/site-packages/conda_build/config.py:--keep-old-work flag not specified.  Removing source and build files.

# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /feedstock_root/build_artefacts/linux-64/pytest-xdist-1.15.0-py27_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 104, in main
    exists = built_distribution_already_exists(cli, meta, owner)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 24, in built_distribution_already_exists
    fname = bldpkg_path(meta)
TypeError: bldpkg_path() missing 1 required positional argument: 'config'
```

Perhaps the feedstock repository should be re-rendered? Is there something I can do to fix it?

**Comment by jakirkham** [comment]
Yep, that's a known issue. Please try [re-rendering](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock) with `conda-smithy`.

**Comment by nicoddemus** [comment]
@jakirkham thanks, I should have read the docs first.

**Comment by jakirkham** [comment]
Maybe we should work to make them easier to find. 😄 At some point am hoping to work on some more docs for Readthedocs to help making things easier to understand/follow. If you have any suggestions on this, please let us know.

**Comment by nicoddemus** [comment]
Will do, thank you! 😄

**Pull request merged**
